dietas <- read.table("dietas.txt", header = TRUE)
colnames(dietas)
mediaa <- mean(dietas$dietaa)
mediab <- mean(dietas$dietab)
mediab1 <- mean(dietas$dietab, trim = 0.1)
mediab2 <- mean(dietas$dietab, trim = 0.2)
mediac <- mean(dietas$dietac)
mediac1 <- mean(dietas$dietac, trim =0.1)
mediac2 <- mean(dietas$dietac, trim = 0.2)
medianaa <- median(dietas$dietaa)
medianab <- median(dietas$dietab)
medianac <- median(dietas$dietac)
mediaa1 <- mean(dietas$dietaa, trim = 0.1)
mediaa2 <- mean(dietas$dietaa, trim = 0.2)

desvioa <- sd(dietas$dietaa)
desviob <- sd(dietas$dietab)
desvioc <- sd(dietas$dietac)
mada <- mad(dietas$dietaa)
madb <- mad(dietas$dietab)
madc<- mad(dietas$dietac)
iqra <- IQR(dietas$dietaa)
iqrb <- IQR(dietas$dietab)
iqrc <- IQR(dietas$dietac)
percentilesa <- quantile(dietas$dietaa, c(0.1,0.25,0.5,0.75,0.9))
percentilesb <- quantile(dietas$dietab)
percentilesc <- quantile(dietas$dietac)


